name: VeritasEngine CI/CD

# The events that will be covered include pushing and merging PRs into main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# This section includes the jobs that will run when the aforementioned
# events occur
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
